BEGIN;

CREATE TABLE "Region" (
    region_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code CHAR(2) NOT NULL UNIQUE,
    name VARCHAR(40) NOT NULL UNIQUE
);

CREATE TABLE "UserType" (
    user_type_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code CHAR(1) NOT NULL UNIQUE CHECK (code IN ('P', 'M', 'A')),
    name VARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE "ServerType" (
    server_type_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(3) NOT NULL UNIQUE CHECK (name IN ('PvP', 'PvE', 'RP'))
);

CREATE TABLE "Faction" (
    faction_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(40) NOT NULL UNIQUE,
    short_description VARCHAR(120) NOT NULL,
    full_description VARCHAR(400) NOT NULL
);

CREATE TABLE "Role" (
    role_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(20) NOT NULL UNIQUE,
    description VARCHAR(200) NOT NULL
);

CREATE TABLE "EventType" (
    event_type_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(12) NOT NULL UNIQUE,
    description VARCHAR(200) NOT NULL
);

CREATE TABLE "Boss" (
    boss_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(60) NOT NULL UNIQUE,
    level SMALLINT NOT NULL CHECK (level >= 1)
);

CREATE TABLE "User" (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_id INTEGER NOT NULL,
    user_type_id INTEGER NOT NULL,
    email VARCHAR(254) NOT NULL UNIQUE,
    nickname VARCHAR(32) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    CONSTRAINT uq_user_id_usertype UNIQUE (user_id, user_type_id),
    CONSTRAINT fk_user_region
        FOREIGN KEY (region_id)
        REFERENCES "Region"(region_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT fk_user_usertype
        FOREIGN KEY (user_type_id)
        REFERENCES "UserType"(user_type_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

CREATE TABLE "Server" (
    server_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_id INTEGER NOT NULL,
    server_type_id INTEGER NOT NULL,
    name VARCHAR(20) NOT NULL UNIQUE,
    CONSTRAINT fk_server_region
        FOREIGN KEY (region_id)
        REFERENCES "Region"(region_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT fk_server_servertype
        FOREIGN KEY (server_type_id)
        REFERENCES "ServerType"(server_type_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

CREATE TABLE "Class" (
    class_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id INTEGER NOT NULL,
    name VARCHAR(30) NOT NULL UNIQUE,
    description VARCHAR(200) NOT NULL,
    CONSTRAINT fk_class_role
        FOREIGN KEY (role_id)
        REFERENCES "Role"(role_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

CREATE TABLE "Race" (
    race_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    faction_id INTEGER NOT NULL,
    name VARCHAR(30) NOT NULL UNIQUE,
    description VARCHAR(200) NOT NULL,
    CONSTRAINT fk_race_faction
        FOREIGN KEY (faction_id)
        REFERENCES "Faction"(faction_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

CREATE TABLE "RaceClassAvailability" (
    race_id INTEGER NOT NULL,
    class_id INTEGER NOT NULL,
    CONSTRAINT pk_raceclassavailability PRIMARY KEY (race_id, class_id),
    CONSTRAINT fk_raceclassavailability_race
        FOREIGN KEY (race_id)
        REFERENCES "Race"(race_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT fk_raceclassavailability_class
        FOREIGN KEY (class_id)
        REFERENCES "Class"(class_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE "Map" (
    map_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type_id INTEGER NOT NULL,
    name VARCHAR(60) NOT NULL,
    CONSTRAINT uq_map_id_event_type UNIQUE (map_id, event_type_id),
    CONSTRAINT uq_map_eventtype_name UNIQUE (event_type_id, name),
    CONSTRAINT fk_map_eventtype
        FOREIGN KEY (event_type_id)
        REFERENCES "EventType"(event_type_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

CREATE TABLE "Character" (
    char_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    server_id INTEGER NOT NULL,
    race_id INTEGER NOT NULL,
    class_id INTEGER NOT NULL,
    name VARCHAR(32) NOT NULL,
    level SMALLINT NOT NULL CHECK (level >= 1),
    gold INTEGER NOT NULL CHECK (gold >= 0),
    avatar VARCHAR(255),
    CONSTRAINT uq_character_server_name UNIQUE (server_id, name),
    CONSTRAINT uq_character_id_server UNIQUE (char_id, server_id),
    CONSTRAINT fk_character_user
        FOREIGN KEY (user_id)
        REFERENCES "User"(user_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT fk_character_server
        FOREIGN KEY (server_id)
        REFERENCES "Server"(server_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT fk_character_race
        FOREIGN KEY (race_id)
        REFERENCES "Race"(race_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT fk_character_class
        FOREIGN KEY (class_id)
        REFERENCES "Class"(class_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT fk_character_race_class_pair
        FOREIGN KEY (race_id, class_id)
        REFERENCES "RaceClassAvailability"(race_id, class_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

CREATE TABLE "Event" (
    event_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    server_id INTEGER NOT NULL,
    event_type_id INTEGER NOT NULL,
    map_id INTEGER NOT NULL,
    status CHAR(1) NOT NULL CHECK (status IN ('C', 'R', 'F')),
    min_level SMALLINT NOT NULL CHECK (min_level >= 1),
    max_level SMALLINT NOT NULL,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP,
    CONSTRAINT chk_event_level_range
        CHECK (max_level >= min_level),
    CONSTRAINT chk_event_time
        CHECK (end_time IS NULL OR end_time >= start_time),
    CONSTRAINT chk_event_status_time
        CHECK (
            (status IN ('C', 'R') AND end_time IS NULL)
            OR
            (status = 'F' AND end_time IS NOT NULL)
        ),
    CONSTRAINT uq_event_id_server UNIQUE (event_id, server_id),
    CONSTRAINT uq_event_id_map UNIQUE (event_id, map_id),
    CONSTRAINT fk_event_server
        FOREIGN KEY (server_id)
        REFERENCES "Server"(server_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT fk_event_eventtype
        FOREIGN KEY (event_type_id)
        REFERENCES "EventType"(event_type_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT fk_event_map_type
        FOREIGN KEY (map_id, event_type_id)
        REFERENCES "Map"(map_id, event_type_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

CREATE TABLE "EventSide" (
    side_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id INTEGER NOT NULL,
    side_number SMALLINT NOT NULL CHECK (side_number IN (1, 2)),
    result CHAR(1) CHECK (result IS NULL OR result IN ('W', 'L')),
    CONSTRAINT uq_eventside_event_side UNIQUE (event_id, side_number),
    CONSTRAINT uq_eventside_eventid_sideid UNIQUE (event_id, side_id),
    CONSTRAINT fk_eventside_event
        FOREIGN KEY (event_id)
        REFERENCES "Event"(event_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE "DungeonBossPool" (
    map_id INTEGER NOT NULL,
    boss_id INTEGER NOT NULL,
    CONSTRAINT pk_dungeonbosspool PRIMARY KEY (map_id, boss_id),
    CONSTRAINT fk_dungeonbosspool_map
        FOREIGN KEY (map_id)
        REFERENCES "Map"(map_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT fk_dungeonbosspool_boss
        FOREIGN KEY (boss_id)
        REFERENCES "Boss"(boss_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE "EventParticipant" (
    event_id INTEGER NOT NULL,
    char_id INTEGER NOT NULL,
    side_id INTEGER NOT NULL,
    server_id INTEGER NOT NULL,
    damage_dealt INTEGER NOT NULL CHECK (damage_dealt >= 0),
    damage_received INTEGER NOT NULL CHECK (damage_received >= 0),
    healing_done INTEGER NOT NULL CHECK (healing_done >= 0),
    kills INTEGER NOT NULL CHECK (kills >= 0),
    CONSTRAINT pk_eventparticipant PRIMARY KEY (event_id, char_id),
    CONSTRAINT fk_eventparticipant_event_server
        FOREIGN KEY (event_id, server_id)
        REFERENCES "Event"(event_id, server_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT fk_eventparticipant_character_server
        FOREIGN KEY (char_id, server_id)
        REFERENCES "Character"(char_id, server_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT fk_eventparticipant_event_side
        FOREIGN KEY (event_id, side_id)
        REFERENCES "EventSide"(event_id, side_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE "EventBoss" (
    event_id INTEGER NOT NULL,
    boss_id INTEGER NOT NULL,
    side_id INTEGER NOT NULL,
    map_id INTEGER NOT NULL,
    CONSTRAINT pk_eventboss PRIMARY KEY (event_id, boss_id),
    CONSTRAINT fk_eventboss_event_map
        FOREIGN KEY (event_id, map_id)
        REFERENCES "Event"(event_id, map_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT fk_eventboss_map_boss
        FOREIGN KEY (map_id, boss_id)
        REFERENCES "DungeonBossPool"(map_id, boss_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT fk_eventboss_event_side
        FOREIGN KEY (event_id, side_id)
        REFERENCES "EventSide"(event_id, side_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE "Ban" (
    ban_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    char_id INTEGER NOT NULL,
    moderator_user_id INTEGER NOT NULL,
    moderator_user_type_id INTEGER NOT NULL DEFAULT 2 CHECK (moderator_user_type_id = 2),
    reason CHAR(3) NOT NULL CHECK (reason IN ('CHT', 'ABU', 'AVA', 'OTH')),
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP,
    CONSTRAINT chk_ban_time
        CHECK (end_time IS NULL OR end_time >= start_time),
    CONSTRAINT fk_ban_character
        FOREIGN KEY (char_id)
        REFERENCES "Character"(char_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT fk_ban_moderator
        FOREIGN KEY (moderator_user_id, moderator_user_type_id)
        REFERENCES "User"(user_id, user_type_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

CREATE INDEX idx_user_region_id ON "User"(region_id);
CREATE INDEX idx_user_user_type_id ON "User"(user_type_id);

CREATE INDEX idx_server_region_id ON "Server"(region_id);
CREATE INDEX idx_server_server_type_id ON "Server"(server_type_id);

CREATE INDEX idx_class_role_id ON "Class"(role_id);
CREATE INDEX idx_race_faction_id ON "Race"(faction_id);

CREATE INDEX idx_character_user_id ON "Character"(user_id);
CREATE INDEX idx_character_server_id ON "Character"(server_id);
CREATE INDEX idx_character_race_id ON "Character"(race_id);
CREATE INDEX idx_character_class_id ON "Character"(class_id);

CREATE INDEX idx_map_event_type_id ON "Map"(event_type_id);

CREATE INDEX idx_event_server_id ON "Event"(server_id);
CREATE INDEX idx_event_event_type_id ON "Event"(event_type_id);
CREATE INDEX idx_event_map_id ON "Event"(map_id);

CREATE INDEX idx_eventside_event_id ON "EventSide"(event_id);

CREATE INDEX idx_eventparticipant_char_server_id ON "EventParticipant"(char_id, server_id);
CREATE INDEX idx_eventparticipant_side_id ON "EventParticipant"(side_id);

CREATE INDEX idx_dungeonbosspool_boss_id ON "DungeonBossPool"(boss_id);

CREATE INDEX idx_eventboss_map_id ON "EventBoss"(map_id);
CREATE INDEX idx_eventboss_side_id ON "EventBoss"(side_id);

CREATE INDEX idx_ban_char_id ON "Ban"(char_id);
CREATE INDEX idx_ban_moderator_user_id ON "Ban"(moderator_user_id);

COMMIT;