BEGIN;

DROP TABLE IF EXISTS "Ban" CASCADE;
DROP TABLE IF EXISTS "EventBoss" CASCADE;
DROP TABLE IF EXISTS "EventParticipant" CASCADE;
DROP TABLE IF EXISTS "DungeonBossPool" CASCADE;
DROP TABLE IF EXISTS "EventSide" CASCADE;
DROP TABLE IF EXISTS "Event" CASCADE;
DROP TABLE IF EXISTS "Character" CASCADE;
DROP TABLE IF EXISTS "Map" CASCADE;
DROP TABLE IF EXISTS "RaceClassAvailability" CASCADE;
DROP TABLE IF EXISTS "Race" CASCADE;
DROP TABLE IF EXISTS "Class" CASCADE;
DROP TABLE IF EXISTS "Boss" CASCADE;
DROP TABLE IF EXISTS "EventType" CASCADE;
DROP TABLE IF EXISTS "Role" CASCADE;
DROP TABLE IF EXISTS "Faction" CASCADE;
DROP TABLE IF EXISTS "Server" CASCADE;
DROP TABLE IF EXISTS "User" CASCADE;
DROP TABLE IF EXISTS "ServerType" CASCADE;
DROP TABLE IF EXISTS "UserType" CASCADE;
DROP TABLE IF EXISTS "Region" CASCADE;

COMMIT;